# Generated by Django 2.2.2 on 2019-06-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artrist', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('uploadFile', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
