# Generated by Django 2.2.2 on 2019-06-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='artrist',
            new_name='artist',
        ),
    ]
