# Generated by Django 2.0.1 on 2019-06-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190613_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='details',
            field=models.CharField(default='rohan', max_length=120),
            preserve_default=False,
        ),
    ]
