# Generated by Django 2.0.1 on 2019-06-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_songs_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
